// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnableTunnel() {
  return window['go']['main']['App']['EnableTunnel']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetWebhookURLs() {
  return window['go']['main']['App']['GetWebhookURLs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
