// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ui} from '../models';

export function CompleteSession(arg1:string,arg2:number):Promise<void>;

export function ConnectSource(arg1:string):Promise<void>;

export function DisconnectSource(arg1:string):Promise<void>;

export function EnableTunnel():Promise<void>;

export function GetCalendarEvents():Promise<Array<main.DashboardEvent>>;

export function GetConfigPaths():Promise<Record<string, string>>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetDashboardHTML():Promise<string>;

export function GetDefaultInfoHTML():Promise<string>;

export function GetDevMode():Promise<boolean>;

export function GetGitHubConfig():Promise<Record<string, any>>;

export function GetGitHubConfigHTML():Promise<string>;

export function GetGitHubToken():Promise<string>;

export function GetGoogleCalendarConfigHTML():Promise<string>;

export function GetPlannedSlots():Promise<Record<string, Array<main.PlannedSlotData>>>;

export function GetPluginInfoHTML(arg1:string):Promise<string>;

export function GetPluginManagerHTML():Promise<string>;

export function GetPlugins():Promise<Array<ui.PluginInfo>>;

export function GetSessionHistory(arg1:string):Promise<Array<main.SessionData>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetSyncDefaultInfoHTML():Promise<string>;

export function GetSyncManagerHTML():Promise<string>;

export function GetSyncSourceInfoHTML(arg1:string):Promise<string>;

export function GetTodayTasks():Promise<Array<main.DashboardTask>>;

export function GetWebhookURLs():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function HasGitHubToken():Promise<boolean>;

export function HasGoogleCredentials():Promise<boolean>;

export function HideWindow():Promise<void>;

export function InstallPlugin(arg1:string):Promise<void>;

export function NavigateToRecord(arg1:string):Promise<void>;

export function PauseSession():Promise<void>;

export function RefreshPluginList():Promise<string>;

export function ReorderTask(arg1:string,arg2:string):Promise<void>;

export function RerenderAll():Promise<void>;

export function RerenderSource(arg1:string):Promise<void>;

export function ResizeTask(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ResumeSession():Promise<void>;

export function ResyncAll():Promise<void>;

export function ResyncSource(arg1:string):Promise<void>;

export function ScheduleTask(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetDevMode(arg1:boolean):Promise<void>;

export function SetGitHubConfig(arg1:boolean,arg2:Array<string>):Promise<void>;

export function SetGitHubRepos(arg1:Array<string>):Promise<void>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function SetGoogleCalendars(arg1:Array<string>):Promise<void>;

export function SetGoogleCredentials(arg1:string):Promise<void>;

export function SetSourceEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function SyncAll():Promise<void>;

export function SyncNow(arg1:string):Promise<void>;

export function ToggleHabit(arg1:string):Promise<void>;

export function UnscheduleTask(arg1:string,arg2:string):Promise<void>;

export function UpdateAllPlugins():Promise<void>;

export function UpdatePlugin(arg1:string):Promise<void>;
