// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSource(arg1) {
  return window['go']['main']['App']['ConnectSource'](arg1);
}

export function DisconnectSource(arg1) {
  return window['go']['main']['App']['DisconnectSource'](arg1);
}

export function EnableTunnel() {
  return window['go']['main']['App']['EnableTunnel']();
}

export function GetConfigPaths() {
  return window['go']['main']['App']['GetConfigPaths']();
}

export function GetDefaultInfoHTML() {
  return window['go']['main']['App']['GetDefaultInfoHTML']();
}

export function GetDevMode() {
  return window['go']['main']['App']['GetDevMode']();
}

export function GetGitHubConfig() {
  return window['go']['main']['App']['GetGitHubConfig']();
}

export function GetGitHubConfigHTML() {
  return window['go']['main']['App']['GetGitHubConfigHTML']();
}

export function GetGitHubToken() {
  return window['go']['main']['App']['GetGitHubToken']();
}

export function GetGoogleCalendarConfigHTML() {
  return window['go']['main']['App']['GetGoogleCalendarConfigHTML']();
}

export function GetPluginInfoHTML(arg1) {
  return window['go']['main']['App']['GetPluginInfoHTML'](arg1);
}

export function GetPluginManagerHTML() {
  return window['go']['main']['App']['GetPluginManagerHTML']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSyncDefaultInfoHTML() {
  return window['go']['main']['App']['GetSyncDefaultInfoHTML']();
}

export function GetSyncManagerHTML() {
  return window['go']['main']['App']['GetSyncManagerHTML']();
}

export function GetSyncSourceInfoHTML(arg1) {
  return window['go']['main']['App']['GetSyncSourceInfoHTML'](arg1);
}

export function GetWebhookURLs() {
  return window['go']['main']['App']['GetWebhookURLs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasGitHubToken() {
  return window['go']['main']['App']['HasGitHubToken']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function RefreshPluginList() {
  return window['go']['main']['App']['RefreshPluginList']();
}

export function SetDevMode(arg1) {
  return window['go']['main']['App']['SetDevMode'](arg1);
}

export function SetGitHubConfig(arg1, arg2) {
  return window['go']['main']['App']['SetGitHubConfig'](arg1, arg2);
}

export function SetGitHubRepos(arg1) {
  return window['go']['main']['App']['SetGitHubRepos'](arg1);
}

export function SetGitHubToken(arg1) {
  return window['go']['main']['App']['SetGitHubToken'](arg1);
}

export function SetGoogleCalendars(arg1) {
  return window['go']['main']['App']['SetGoogleCalendars'](arg1);
}

export function SetSourceEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSourceEnabled'](arg1, arg2);
}

export function SyncAll() {
  return window['go']['main']['App']['SyncAll']();
}

export function SyncNow(arg1) {
  return window['go']['main']['App']['SyncNow'](arg1);
}

export function UpdateAllPlugins() {
  return window['go']['main']['App']['UpdateAllPlugins']();
}

export function UpdatePlugin(arg1) {
  return window['go']['main']['App']['UpdatePlugin'](arg1);
}
